### create product
POST http://localhost:5000/api/products
Content-Type: application/json

{
  "name": "Asus Zenbook Duo 2025",
  "description": "A high-performance laptop",
  "category": "Electronics",
  "price": 1500,
  "stock_quantity": 10,
  "image_url": "https://cdn.mos.cms.futurecdn.net/tmorTeJxdHu6zvh6oVxGoQ.jpg"
}

### create product
POST http://localhost:5000/api/products
Content-Type: application/json

{
  "name": "Asus Zenbook Duo 2025 (1)",
  "description": "A high-performance laptop",
  "category": "Electronics",
  "price": 1500,
  "stock_quantity": 10,
  "image_url": "https://cdn.mos.cms.futurecdn.net/tmorTeJxdHu6zvh6oVxGoQ.jpg"
}

### create product
POST http://localhost:5000/api/products
Content-Type: application/json

{
  "name": "Asus Zenbook Duo 2025 (2)",
  "description": "A high-performance laptop",
  "category": "Electronics",
  "price": 1500,
  "stock_quantity": 10,
  "image_url": "https://cdn.mos.cms.futurecdn.net/tmorTeJxdHu6zvh6oVxGoQ.jpg"
}